# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('tipo', models.CharField(blank=True, max_length=25, null=True)),
                ('descrição', models.TextField(blank=True, max_length=300, null=True)),
                ('data', models.CharField(blank=True, max_length=15, null=True)),
                ('granulometria', models.FileField(blank=True, null=True, upload_to='')),
                ('coletador', models.CharField(blank=True, max_length=50, null=True)),
                ('Contato', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem1', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem2', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem3', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem4', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem5', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem6', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem7', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem8', models.FileField(blank=True, null=True, upload_to='')),
                ('Ambientes', models.ManyToManyField(blank=True, to='catalogação.Ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=55, null=True)),
                ('geologia', models.TextField(blank=True, max_length=300, null=True)),
                ('is_destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Cidades', models.ManyToManyField(blank=True, to='catalogação.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('sigla', models.CharField(max_length=10)),
                ('is_destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=55, null=True)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Continentes', models.ManyToManyField(blank=True, to='catalogação.Continente')),
            ],
        ),
        migrations.CreateModel(
            name='País',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('região', models.CharField(blank=True, max_length=25, null=True)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Continentes', models.ManyToManyField(blank=True, to='catalogação.Continente')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='catalogação.País'),
        ),
        migrations.AddField(
            model_name='clima',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='catalogação.Continente'),
        ),
        migrations.AddField(
            model_name='clima',
            name='Estados',
            field=models.ManyToManyField(blank=True, to='catalogação.Estado'),
        ),
        migrations.AddField(
            model_name='clima',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='catalogação.País'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='catalogação.Continente'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='Estados',
            field=models.ManyToManyField(blank=True, to='catalogação.Estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='catalogação.País'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Cidades',
            field=models.ManyToManyField(blank=True, to='catalogação.Cidade'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Climas',
            field=models.ManyToManyField(blank=True, to='catalogação.Clima'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='catalogação.Continente'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Estados',
            field=models.ManyToManyField(blank=True, to='catalogação.Estado'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='catalogação.País'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='Cidades',
            field=models.ManyToManyField(blank=True, to='catalogação.Cidade'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='catalogação.Continente'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='Estados',
            field=models.ManyToManyField(blank=True, to='catalogação.Estado'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='catalogação.País'),
        ),
    ]
