# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ambi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='amostr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=25)),
                ('descrição', models.TextField(blank=True, max_length=300, null=True)),
                ('data', models.CharField(blank=True, max_length=15, null=True)),
                ('granulometria', models.FileField(blank=True, null=True, upload_to='')),
                ('coletador', models.CharField(blank=True, max_length=50, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem1', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem2', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem3', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem4', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem5', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem6', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem7', models.FileField(blank=True, null=True, upload_to='')),
                ('imagem8', models.FileField(blank=True, null=True, upload_to='')),
                ('Ambientes', models.ManyToManyField(blank=True, through='amostras.amostr', to='amostras.Ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=55, null=True)),
                ('geologia', models.TextField(blank=True, max_length=300, null=True)),
                ('is_destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='clim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Cidades', models.ManyToManyField(blank=True, through='amostras.clim', to='amostras.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Conti_país',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('is_destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=55, null=True)),
                ('is_destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='País',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('região', models.CharField(blank=True, max_length=25, null=True)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Continentes', models.ManyToManyField(blank=True, through='amostras.Conti_país', to='amostras.Continente')),
            ],
        ),
        migrations.CreateModel(
            name='País_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Estado')),
                ('país', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.País')),
            ],
        ),
        migrations.CreateModel(
            name='País_estado_cid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Estado')),
                ('país', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.País')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='Paíss',
            field=models.ManyToManyField(blank=True, through='amostras.País_estado', to='amostras.País'),
        ),
        migrations.AddField(
            model_name='conti_país',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Continente'),
        ),
        migrations.AddField(
            model_name='conti_país',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.País'),
        ),
        migrations.AddField(
            model_name='clima',
            name='Estados',
            field=models.ManyToManyField(blank=True, through='amostras.clim', to='amostras.Estado'),
        ),
        migrations.AddField(
            model_name='clima',
            name='Paíss',
            field=models.ManyToManyField(blank=True, through='amostras.clim', to='amostras.País'),
        ),
        migrations.AddField(
            model_name='clim',
            name='clima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Clima'),
        ),
        migrations.AddField(
            model_name='clim',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Estado'),
        ),
        migrations.AddField(
            model_name='clim',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.País'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='Estados',
            field=models.ManyToManyField(blank=True, through='amostras.País_estado_cid', to='amostras.Estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='Paíss',
            field=models.ManyToManyField(blank=True, through='amostras.País_estado_cid', to='amostras.País'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Cidades',
            field=models.ManyToManyField(blank=True, through='amostras.amostr', to='amostras.Cidade'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Climas',
            field=models.ManyToManyField(blank=True, through='amostras.amostr', to='amostras.Clima'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Continentes',
            field=models.ManyToManyField(blank=True, through='amostras.amostr', to='amostras.Continente'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Estados',
            field=models.ManyToManyField(blank=True, through='amostras.amostr', to='amostras.Estado'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Países',
            field=models.ManyToManyField(blank=True, through='amostras.amostr', to='amostras.País'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amostr',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Amostra'),
        ),
        migrations.AddField(
            model_name='amostr',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Cidade'),
        ),
        migrations.AddField(
            model_name='amostr',
            name='clima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Clima'),
        ),
        migrations.AddField(
            model_name='amostr',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Continente'),
        ),
        migrations.AddField(
            model_name='amostr',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Estado'),
        ),
        migrations.AddField(
            model_name='amostr',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.País'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='Cidades',
            field=models.ManyToManyField(blank=True, through='amostras.ambi', to='amostras.Cidade'),
        ),
        migrations.AddField(
            model_name='ambi',
            name='Cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Cidade'),
        ),
        migrations.AddField(
            model_name='ambi',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostras.Ambiente'),
        ),
    ]
