# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0002_auto_20170307_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='CLimas',
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='Paíss',
        ),
        migrations.AddField(
            model_name='amostra',
            name='Climas',
            field=models.ManyToManyField(blank=True, to='amostras.Clima'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='Países',
            field=models.ManyToManyField(blank=True, to='amostras.País'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='Cidades',
            field=models.ManyToManyField(blank=True, to='amostras.Cidade'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='amostras.Continente'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='Estados',
            field=models.ManyToManyField(blank=True, to='amostras.Estado'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='amostras.País'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Ambientes',
            field=models.ManyToManyField(blank=True, to='amostras.Ambiente'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Cidades',
            field=models.ManyToManyField(blank=True, to='amostras.Cidade'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='amostras.Continente'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='Estados',
            field=models.ManyToManyField(blank=True, to='amostras.Estado'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='tipo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='amostras.Continente'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='Estados',
            field=models.ManyToManyField(blank=True, to='amostras.Estado'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='amostras.País'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='Cidades',
            field=models.ManyToManyField(blank=True, to='amostras.Cidade'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='amostras.Continente'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='Estados',
            field=models.ManyToManyField(blank=True, to='amostras.Estado'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='amostras.País'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='amostras.Continente'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='Paíss',
            field=models.ManyToManyField(blank=True, to='amostras.País'),
        ),
        migrations.AlterField(
            model_name='país',
            name='Continentes',
            field=models.ManyToManyField(blank=True, to='amostras.Continente'),
        ),
    ]
