# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0003_auto_20170323_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amostra',
            old_name='Países',
            new_name='Paíss',
        ),
    ]
