# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0005_auto_20170324_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='Países',
            new_name='Paíss',
        ),
        migrations.RenameField(
            model_name='amostra',
            old_name='Países',
            new_name='Paíss',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='Países',
            new_name='Paíss',
        ),
        migrations.RenameField(
            model_name='clima',
            old_name='Países',
            new_name='Paíss',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='Países',
            new_name='Paíss',
        ),
    ]
