# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('ambiente', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=25)),
                ('descrição', models.TextField(max_length=200)),
                ('data', models.CharField(max_length=15)),
                ('granulometria', models.CharField(max_length=15)),
                ('imagem', models.CharField(max_length=1500)),
                ('imagem2', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('geologia', models.TextField(max_length=255)),
                ('graus', models.CharField(max_length=15)),
                ('minutos', models.CharField(max_length=15)),
                ('segundos', models.CharField(max_length=15)),
                ('UTM', models.CharField(max_length=15)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Amostra')),
            ],
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Amostra')),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Coletador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Amostra')),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('sigla', models.CharField(max_length=15)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Amostra')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Amostra')),
                ('Continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Continente')),
            ],
        ),
        migrations.CreateModel(
            name='País',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('região', models.CharField(max_length=20)),
                ('is_destaque', models.BooleanField(default=False)),
                ('Amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Amostra')),
                ('Continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Continente')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='País',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.País'),
        ),
        migrations.AddField(
            model_name='coletador',
            name='Continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Continente'),
        ),
        migrations.AddField(
            model_name='coletador',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Estado'),
        ),
        migrations.AddField(
            model_name='coletador',
            name='País',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.País'),
        ),
        migrations.AddField(
            model_name='clima',
            name='Continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Continente'),
        ),
        migrations.AddField(
            model_name='clima',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Estado'),
        ),
        migrations.AddField(
            model_name='clima',
            name='País',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.País'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='Continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Continente'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.Estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='País',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amostra.País'),
        ),
    ]
