# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='imagem',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='imagem2',
            field=models.FileField(upload_to=''),
        ),
    ]
