# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostra', '0003_auto_20161210_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coletador',
            name='Amostra',
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='Cidade',
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='Continente',
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='País',
        ),
        migrations.AddField(
            model_name='amostra',
            name='coletador',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coletador',
        ),
    ]
