# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amostra', '0004_auto_20161210_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='continente',
            new_name='Continente',
        ),
        migrations.RenameField(
            model_name='ambiente',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
