# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedimentos', '0002_auto_20170106_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Amostra'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Cidade'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Continente'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Estado'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.País'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='granulometria',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Amostra'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Continente'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Estado'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.País'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Amostra'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Cidade'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Continente'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Estado'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.País'),
        ),
        migrations.AlterField(
            model_name='continente',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Amostra'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Amostra'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Continente'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.País'),
        ),
        migrations.AlterField(
            model_name='país',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Amostra'),
        ),
        migrations.AlterField(
            model_name='país',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.Continente'),
        ),
    ]
