# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('ambiente', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('descrição', models.TextField(max_length=150)),
                ('data', models.CharField(max_length=15)),
                ('granulometria', models.CharField(max_length=15)),
                ('graus', models.CharField(max_length=15)),
                ('minutos', models.CharField(max_length=15)),
                ('segundos', models.CharField(max_length=15)),
                ('UTM', models.CharField(max_length=15)),
                ('imagem', models.CharField(max_length=1500)),
                ('imagem2', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('geologia', models.TextField(max_length=215)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.amostra')),
            ],
        ),
        migrations.CreateModel(
            name='clima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.amostra')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='coletador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come', models.CharField(max_length=15)),
                ('país', models.CharField(max_length=15)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.amostra')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('sigla', models.CharField(max_length=15)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.amostra')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.amostra')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.continente')),
            ],
        ),
        migrations.CreateModel(
            name='país',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('região', models.CharField(max_length=15)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.amostra')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.continente')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.país'),
        ),
        migrations.AddField(
            model_name='coletador',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.continente'),
        ),
        migrations.AddField(
            model_name='coletador',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.estado'),
        ),
        migrations.AddField(
            model_name='clima',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.continente'),
        ),
        migrations.AddField(
            model_name='clima',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.estado'),
        ),
        migrations.AddField(
            model_name='clima',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.país'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.continente'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.país'),
        ),
    ]
