# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='amostra',
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='continente',
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='coletador',
            name='país',
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='UTM',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='graus',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='minutos',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='segundos',
        ),
        migrations.AddField(
            model_name='amostra',
            name='coletador',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amostra',
            name='descrição',
            field=models.TextField(max_length=300),
        ),
        migrations.DeleteModel(
            name='coletador',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.amostra'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.cidade'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='continente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.continente'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.estado'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='país',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedimentos.país'),
        ),
    ]
