# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedimentos', '0002_auto_20161122_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='imagem',
            field=models.FileField(upload_to=''),
        ),
    ]
