# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedimentos', '0003_auto_20161122_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='tipo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='coletador',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='data',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='descrição',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='imagem',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='geologia',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clima',
            name='tipo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='continente',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='continente',
            name='sigla',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='país',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='país',
            name='região',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
