# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedimentos', '0003_auto_20161119_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='is_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clima',
            name='is_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coletador',
            name='is_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='continente',
            name='is_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estado',
            name='is_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='país',
            name='is_destaque',
            field=models.BooleanField(default=False),
        ),
    ]
